[versions]
latestTestNG = "7.12.0" # Keep in sync with TestContext.java and README.adoc
snapshotTestNG = "7.13.0-SNAPSHOT"
latestJUnit = "6.0.1"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.7" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.20.0" }
junit4 = { module = "junit:junit", version = "4.13.2" }
junit-bom = { module = "org.junit:junit-bom", version = "5.7.2" }
latest-junit-bom = { module = "org.junit:junit-bom", version.ref = "latestJUnit" }
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version = "2.25.3" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version = "3.9.12" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version = "5.21.0" }
testng = { module = "org.testng:testng", version.ref = "latestTestNG" }
